name: mspr_coffee_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+3

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.5
  go_router: ^4.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  flutter_side_menu: ^0.2.0
  glass_kit: ^2.0.1
  iconsax: ^0.0.8
  form_field_validator: ^1.1.0
  firebase_auth: ^4.1.5
  flutter_secure_storage: ^8.0.0
  cloud_firestore: ^4.4.3
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.3
  firebase_dynamic_links: ^5.0.15
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.1.1
  functional_data_generator: ^1.1.4
  json_serializable: ^6.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/images/
