# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
        api_key = app_store_connect_api_key(
      key_id: "Q6PXB457PH",
      issuer_id: "2174b29f-1a4b-40d9-8f5a-7c4ed51a8189",
      key_filepath: "../../AuthKey_Q6PXB457PH.p8",
      duration: 1200, # optional
      in_house: false # optional
    )
    match(      
      type: 'appstore', 
      app_identifier: ["com.blecat.msprCoffeeApp"],
      api_key: api_key,
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "app-store")
    upload_to_testflight
  end
end
