name: Flutter Deploy IOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.2"
      - uses: actions/checkout@v2
      - name: Bundle install
        run: cd ./ios && bundle install
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.7"
          channel: "stable"
      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      - name: Download AppleAuthKey and GCloud KeyFile Json from GCP bucket
        run: |
          pwd
          ls
          gsutil cp gs://'${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}'/'${{ secrets.APPLE_AUTH_KEY_FILENAME }}' .
          gsutil cp gs://'${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}'/'${{ secrets.GOOGLE_CLOUD_KEY_FILENAME }}' ./mspr_coffee_app/ios/'${{ secrets.GOOGLE_CLOUD_KEY_FILENAME }}'
      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: beta
          subdirectory: ios
        env:
          DEVELOPER_APP_IDENTIFIER: "${{ secrets.DEVELOPER_APP_IDENTIFIER }}"
          APPLE_DEVELOPER_USERNAME: "${{ secrets.APPLE_DEVELOPER_USERNAME }}"
          APPLE_AUTH_KEY_ID: "${{ secrets.APPLE_AUTH_KEY_ID }}"
          APPLE_AUTH_ISSUER_ID: "${{ secrets.APPLE_AUTH_ISSUER_ID }}"
          APPLE_AUTH_KEY_PATH: "${{ secrets.APPLE_AUTH_KEY_PATH }}"
          FASTLANE_APPLE_ID: "${{ secrets.FASTLANE_APPLE_ID }}"
          APP_STORE_CONNECT_TEAM_ID: "${{ secrets.APP_STORE_CONNECT_TEAM_ID }}"
          DEVELOPER_PORTAL_TEAM_ID: "${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}"
          MATCH_KEYCHAIN_PASSWORD: "${{ secrets.MATCH_KEYCHAIN_PASSWORD }}"
          GOOGLE_CLOUD_BUCKET_NAME: "${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}"
          GOOGLE_CLOUD_PROJECT_ID: "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"